[package]
name = "autonomous"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.10", features = ["dynamic_linking"] }

[workspace]
resolver = "2"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

